# Generated by Django 4.1.7 on 2023-02-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0003_monsters_spells_weapons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
