# Generated by Django 4.1.7 on 2023-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0004_delete_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='puntaje',
            field=models.FloatField(default=0),
        ),
    ]
