# Generated by Django 4.1.7 on 2023-02-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0007_weapons_descripcion_weapons_legendaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='descripcion',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='spells',
            name='opinion',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
