# Generated by Django 4.1.7 on 2023-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0009_alter_spells_opinion_alter_weapons_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='descripcion',
            field=models.TextField(default='nadie', max_length=1000),
        ),
    ]
