# Generated by Django 4.1.7 on 2023-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0011_alter_weapons_descripcion_alter_weapons_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='descripcion',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='spells',
            name='opinion',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='descripcion',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='opinion',
            field=models.TextField(default='', max_length=200),
        ),
    ]
