# Generated by Django 4.1.7 on 2023-02-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0013_weapons_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellsReseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(default=0)),
                ('opinion', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='spells',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='puntaje',
        ),
    ]
