# Generated by Django 4.1.7 on 2023-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0015_spellsreseñas_nombre_spellsreseñas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='imagen',
            field=models.ImageField(default='FamilyApp/assets/img/blank.png', upload_to='FamilyApp/assets/img/'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='imagen',
            field=models.ImageField(default='FamilyApp/assets/img/blank.png', upload_to='FamilyApp/assets/img/'),
        ),
    ]
