# Generated by Django 4.1.7 on 2023-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0016_spells_imagen_alter_weapons_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
